// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wise.proto

package v0

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SelectRequest struct {
	Table                *TableLocation                        `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Sfr                  *PlainSelectFilterReduceConfiguration `protobuf:"bytes,2,opt,name=sfr,proto3" json:"sfr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *SelectRequest) Reset()         { *m = SelectRequest{} }
func (m *SelectRequest) String() string { return proto.CompactTextString(m) }
func (*SelectRequest) ProtoMessage()    {}
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f998c9f74babd757, []int{0}
}

func (m *SelectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectRequest.Unmarshal(m, b)
}
func (m *SelectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectRequest.Marshal(b, m, deterministic)
}
func (m *SelectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectRequest.Merge(m, src)
}
func (m *SelectRequest) XXX_Size() int {
	return xxx_messageInfo_SelectRequest.Size(m)
}
func (m *SelectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectRequest proto.InternalMessageInfo

func (m *SelectRequest) GetTable() *TableLocation {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *SelectRequest) GetSfr() *PlainSelectFilterReduceConfiguration {
	if m != nil {
		return m.Sfr
	}
	return nil
}

type WiseInfo struct {
	Table                *TableLocation `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Content              []*WiseElement `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WiseInfo) Reset()         { *m = WiseInfo{} }
func (m *WiseInfo) String() string { return proto.CompactTextString(m) }
func (*WiseInfo) ProtoMessage()    {}
func (*WiseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f998c9f74babd757, []int{1}
}

func (m *WiseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WiseInfo.Unmarshal(m, b)
}
func (m *WiseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WiseInfo.Marshal(b, m, deterministic)
}
func (m *WiseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WiseInfo.Merge(m, src)
}
func (m *WiseInfo) XXX_Size() int {
	return xxx_messageInfo_WiseInfo.Size(m)
}
func (m *WiseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WiseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WiseInfo proto.InternalMessageInfo

func (m *WiseInfo) GetTable() *TableLocation {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *WiseInfo) GetContent() []*WiseElement {
	if m != nil {
		return m.Content
	}
	return nil
}

type WiseElement struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Un                   string   `protobuf:"bytes,2,opt,name=un,proto3" json:"un,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WiseElement) Reset()         { *m = WiseElement{} }
func (m *WiseElement) String() string { return proto.CompactTextString(m) }
func (*WiseElement) ProtoMessage()    {}
func (*WiseElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_f998c9f74babd757, []int{2}
}

func (m *WiseElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WiseElement.Unmarshal(m, b)
}
func (m *WiseElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WiseElement.Marshal(b, m, deterministic)
}
func (m *WiseElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WiseElement.Merge(m, src)
}
func (m *WiseElement) XXX_Size() int {
	return xxx_messageInfo_WiseElement.Size(m)
}
func (m *WiseElement) XXX_DiscardUnknown() {
	xxx_messageInfo_WiseElement.DiscardUnknown(m)
}

var xxx_messageInfo_WiseElement proto.InternalMessageInfo

func (m *WiseElement) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *WiseElement) GetUn() string {
	if m != nil {
		return m.Un
	}
	return ""
}

func init() {
	proto.RegisterType((*SelectRequest)(nil), "mechelia.v0.SelectRequest")
	proto.RegisterType((*WiseInfo)(nil), "mechelia.v0.WiseInfo")
	proto.RegisterType((*WiseElement)(nil), "mechelia.v0.WiseElement")
}

func init() { proto.RegisterFile("wise.proto", fileDescriptor_f998c9f74babd757) }

var fileDescriptor_f998c9f74babd757 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x41, 0x4b, 0xfc, 0x30,
	0x10, 0xc5, 0xd9, 0xf6, 0xff, 0x5f, 0xdd, 0xa9, 0x8a, 0x46, 0x84, 0xd2, 0xd3, 0xd2, 0xd3, 0x5e,
	0x6c, 0x6b, 0x3d, 0x7a, 0xb3, 0x28, 0x08, 0x1e, 0x24, 0x0a, 0x82, 0xb7, 0x6e, 0x76, 0x5a, 0x03,
	0xe9, 0x64, 0x6d, 0x93, 0xf5, 0x1b, 0xf8, 0xb9, 0x25, 0x29, 0xc2, 0x16, 0x6f, 0xde, 0xc2, 0xcc,
	0xfb, 0xbd, 0xbc, 0x37, 0x00, 0x9f, 0x72, 0xc0, 0x6c, 0xdb, 0x6b, 0xa3, 0x59, 0xd4, 0xa1, 0x78,
	0x47, 0x25, 0xeb, 0x6c, 0x57, 0x24, 0x47, 0x42, 0x77, 0x9d, 0xa6, 0x71, 0x95, 0x7e, 0xcd, 0xe0,
	0xf8, 0x19, 0x15, 0x0a, 0xc3, 0xf1, 0xc3, 0xe2, 0x60, 0x58, 0x01, 0xff, 0x4d, 0xbd, 0x56, 0x18,
	0xcf, 0x96, 0xb3, 0x55, 0x54, 0x26, 0xd9, 0x1e, 0x9c, 0xbd, 0xb8, 0xcd, 0xa3, 0x16, 0xb5, 0x91,
	0x9a, 0xf8, 0x28, 0x64, 0x15, 0x84, 0x43, 0xd3, 0xc7, 0x81, 0xd7, 0x5f, 0x4d, 0xf4, 0x4f, 0xaa,
	0x96, 0x34, 0xfa, 0xdf, 0x4b, 0x65, 0xb0, 0xe7, 0xb8, 0xb1, 0x02, 0x2b, 0x4d, 0x8d, 0x6c, 0x6d,
	0x3f, 0xda, 0x38, 0x3a, 0xdd, 0xc2, 0xe1, 0xab, 0x1c, 0xf0, 0x81, 0x1a, 0xfd, 0x87, 0x08, 0x25,
	0x1c, 0x08, 0x4d, 0x06, 0xc9, 0xc4, 0xc1, 0x32, 0x5c, 0x45, 0x65, 0x3c, 0x61, 0x9c, 0xf3, 0x9d,
	0xc2, 0x0e, 0xc9, 0xf0, 0x1f, 0x61, 0x9a, 0x43, 0xb4, 0x37, 0x67, 0xa7, 0x10, 0x5a, 0xb9, 0xf1,
	0x5f, 0x2e, 0xb8, 0x7b, 0xb2, 0x13, 0x08, 0x2c, 0xf9, 0x5a, 0x0b, 0x1e, 0x58, 0x2a, 0x2b, 0xf8,
	0xe7, 0x00, 0x76, 0x03, 0xf3, 0xc1, 0x57, 0x62, 0xd3, 0x64, 0x93, 0x3b, 0x26, 0x17, 0xbf, 0x12,
	0xb8, 0x6e, 0xb7, 0xe7, 0x6f, 0x67, 0x59, 0xee, 0x6f, 0x7f, 0xd9, 0x6a, 0x55, 0x53, 0x9b, 0xef,
	0x8a, 0xf5, 0xdc, 0x0f, 0xae, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x38, 0x10, 0x5c, 0x53, 0xb5,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WiseClient is the client API for Wise service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WiseClient interface {
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*WiseInfo, error)
}

type wiseClient struct {
	cc *grpc.ClientConn
}

func NewWiseClient(cc *grpc.ClientConn) WiseClient {
	return &wiseClient{cc}
}

func (c *wiseClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*WiseInfo, error) {
	out := new(WiseInfo)
	err := c.cc.Invoke(ctx, "/mechelia.v0.Wise/select", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WiseServer is the server API for Wise service.
type WiseServer interface {
	Select(context.Context, *SelectRequest) (*WiseInfo, error)
}

// UnimplementedWiseServer can be embedded to have forward compatible implementations.
type UnimplementedWiseServer struct {
}

func (*UnimplementedWiseServer) Select(ctx context.Context, req *SelectRequest) (*WiseInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Select not implemented")
}

func RegisterWiseServer(s *grpc.Server, srv WiseServer) {
	s.RegisterService(&_Wise_serviceDesc, srv)
}

func _Wise_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiseServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechelia.v0.Wise/Select",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiseServer).Select(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wise_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mechelia.v0.Wise",
	HandlerType: (*WiseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "select",
			Handler:    _Wise_Select_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wise.proto",
}
